export const events = [
  {
    id: 1,
    title: "Tech Conference 2025",
    date: "Sunday, 14 April 2025",
    time: "09:00 AM - 05:00 PM",
    location: "San Francisco, CA",
    description: "A one-day tech event bringing together developers, startups, and industry leaders to explore the future of AI, blockchain, and cloud computing.",
    capacity: 100,
    tags: ["tech", "conference", "innovation"],
    image: "/placeholder.png",
    spotsLeft: 20,
    isPast: false,
  },
  {
    id: 2,
    title: "Tech Conference 2024",
    date: "Sunday, 14 April 2024",
    time: "09:00 AM - 05:00 PM",
    location: "San Francisco, CA",
    description: "Past tech conference focused on AI and innovation.",
    capacity: 100,
    tags: ["tech", "conference"],
    image: "/placeholder.png",
    spotsLeft: 0,
    isPast: true,
  },
  {
    id: 3,
    title: "AI Summit 2025",
    date: "Friday, 20 June 2025",
    time: "10:00 AM - 06:00 PM",
    location: "New York, NY",
    description: "A summit dedicated to the latest advancements in artificial intelligence and machine learning.",
    capacity: 150,
    tags: ["ai", "summit", "technology"],
    image: "/placeholder.png",
    spotsLeft: 30,
    isPast: false,
  },
  {
    id: 4,
    title: "Blockchain Expo 2023",
    date: "Monday, 15 May 2023",
    time: "09:00 AM - 04:00 PM",
    location: "London, UK",
    description: "An expo showcasing the future of blockchain technology and cryptocurrency.",
    capacity: 80,
    tags: ["blockchain", "expo", "crypto"],
    image: "/placeholder.png",
    spotsLeft: 0,
    isPast: true,
  },
  {
    id: 5,
    title: "Cloud Computing Workshop 2025",
    date: "Wednesday, 10 July 2025",
    time: "01:00 PM - 05:00 PM",
    location: "Seattle, WA",
    description: "Hands-on workshop on cloud computing solutions and best practices.",
    capacity: 50,
    tags: ["cloud", "workshop", "tech"],
    image: "/placeholder.png",
    spotsLeft: 10,
    isPast: false,
  },
  {
    id: 6,
    title: "Startup Pitch Day 2024",
    date: "Tuesday, 25 June 2024",
    time: "11:00 AM - 03:00 PM",
    location: "Austin, TX",
    description: "An event for startups to pitch their ideas to investors and mentors.",
    capacity: 70,
    tags: ["startup", "pitch", "business"],
    image: "/placeholder.png",
    spotsLeft: 0,
    isPast: true,
  },
  {
    id: 7,
    title: "DevFest 2025",
    date: "Saturday, 5 September 2025",
    time: "09:00 AM - 06:00 PM",
    location: "Chicago, IL",
    description: "A festival for developers to learn, network, and showcase projects.",
    capacity: 200,
    tags: ["dev", "festival", "coding"],
    image: "/placeholder.png",
    spotsLeft: 50,
    isPast: false,
  },
  {
    id: 8,
    title: "Cybersecurity Symposium 2023",
    date: "Thursday, 20 October 2023",
    time: "10:00 AM - 04:00 PM",
    location: "Boston, MA",
    description: "Symposium on the latest trends and challenges in cybersecurity.",
    capacity: 90,
    tags: ["cybersecurity", "symposium", "security"],
    image: "/placeholder.png",
    spotsLeft: 0,
    isPast: true,
  },
  {
    id: 9,
    title: "Data Science Meetup 2025",
    date: "Monday, 15 August 2025",
    time: "02:00 PM - 06:00 PM",
    location: "Toronto, ON",
    description: "A meetup for data scientists to share insights and collaborate.",
    capacity: 60,
    tags: ["data", "science", "meetup"],
    image: "/placeholder.png",
    spotsLeft: 15,
    isPast: false,
  },
  {
    id: 10,
    title: "IoT Innovation Day 2024",
    date: "Wednesday, 12 March 2024",
    time: "09:00 AM - 03:00 PM",
    location: "Vancouver, BC",
    description: "A day focused on innovations in Internet of Things technology.",
    capacity: 75,
    tags: ["iot", "innovation", "tech"],
    image: "/placeholder.png",
    spotsLeft: 0,
    isPast: true,
  },
  {
    id: 11,
    title: "Web Development Bootcamp 2025",
    date: "Friday, 25 July 2025",
    time: "09:00 AM - 05:00 PM",
    location: "Los Angeles, CA",
    description: "Intensive bootcamp for learning modern web development techniques.",
    capacity: 40,
    tags: ["web", "development", "bootcamp"],
    image: "/placeholder.png",
    spotsLeft: 8,
    isPast: false,
  },
  {
    id: 12,
    title: "Machine Learning Forum 2023",
    date: "Saturday, 18 November 2023",
    time: "10:00 AM - 04:00 PM",
    location: "Sydney, AU",
    description: "Forum discussing the latest in machine learning applications.",
    capacity: 100,
    tags: ["machine", "learning", "forum"],
    image: "/placeholder.png",
    spotsLeft: 0,
    isPast: true,
  },
];

export const bookings = [];